create table if not exists public.leads (id bigint generated by default as identity primary key, created_at timestamptz not null default now(), name text not null, email text not null, company text, website text, service text, budget text, message text not null);
alter table public.leads enable row level security;
revoke all on public.leads from anon, authenticated;
